apiVersion: apps/v1
kind: Deployment
metadata:
  name: $K8S_SERVICE_NAME
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1                     
  selector:
    matchLabels:
      app: $K8S_SERVICE_NAME
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: $K8S_SERVICE_NAME
      annotations:
        kubernetes.io/change-cause: "$K8S_CHANGE_CAUSE"
    spec:
      containers:
      - name: $K8S_SERVICE_NAME
        image: $DOCKER_TAG
        resources:
          requests:
            cpu: "700m"
            memory: "3Gi"
          limits:
            cpu: "1"
            memory: "4Gi"
        ports:
          - name: $CONTAINER_PORT_NAME
            containerPort: $K8S_CONTAINER_PORT              
      imagePullSecrets:
      - name: imagerepo.gems.gov.bd
      hostAliases:
        - ip: 172.22.177.83
          hostnames:
            - api.gems.gov.bd